from typing import Dict
from pydantic import BaseModel
from pydantic.errors import ArbitraryTypeError

class IndicadorInDB(BaseModel):
	id_indicador: int = 0
	name: str
	porcentaje: float
	gerencia: str
	central: str
	colorin: str
	formula: str
	calculo: str
	comentario: str
	ponderado: float
	lgreen: float
	lyellow: str
	lred: float

database_indicadores = Dict[str, IndicadorInDB]
database_indicadores = {
	"Indicador3": IndicadorInDB(**{"id_indicador": 3,
							"name":"Cajeros: Up time cajeros NCR",
							"porcentaje":96.9,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Up time cajeros NCR",
							"calculo":"Cantidad de cajeros: 501",
							"comentario":"up time semanal del 03 al 09 de junio - incremento en fallas y tiempos de atención de cajeros, asi como afectación por mantenimientos preventivos. Se estima recuperación en la siguiente semana",
							"ponderado":97.6,
							"lgreen":97,
							"lyellow":"N/A",
							"lred":97}),
	"Indicador4": IndicadorInDB(**{"id_indicador": 4,
							"name":"Cajeros: Up time cajeros DIEBOLD",
							"porcentaje":96.3,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Up time cajeros DIEBOLD",
							"calculo":"Cantidad de cajeros: 191",
							"comentario":"up time semanal del 03 al 09 de junio - incremento en fallas y tiempos de atención de cajeros, asi como afectación por mantenimientos preventivos. Se estima recuperación en la siguiente semana",
							"ponderado":97.0,
							"lgreen":97,
							"lyellow":"N/A",
							"lred":97}),
	"Indicador2": IndicadorInDB(**{"id_indicador": 2,
							"name":"Cajeros: Up time Multifuncionales DIEBOLD",
							"porcentaje":91.7,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Up time Multifuncionales DIEBOLD",
							"calculo":"Cantidad de MF: 56",
							"comentario":"up time semanal del 03 al 09 de junio - incremento en fallas y tiempos de atención de cajeros, asi como afectación por mantenimientos preventivos. Se estima recuperación en la siguiente semana",
							"ponderado":93.9,
							"lgreen":95,
							"lyellow":"94",
							"lred":94}),
	"Indicador1": IndicadorInDB(**{"id_indicador": 1,
							"name":"Efectivo: Cumplimiento Saldo de Caja",
							"porcentaje":90.0,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"1. Red",
							"formula":"Total meta  / Total promedio semana (meta  para el 2021:  $570,000,000,000 promd)",
							"calculo":"Saldo promedio: $632.741.402.076",
							"comentario":"Semana 03 al 09 de junio 2021 La variación obedece a mayor demanda de efectivo por pago de primas, vacaciones y pago pensionados",
							"ponderado":97.2,
							"lgreen":100,
							"lyellow":"95",
							"lred":95}),
	"Indicador9": IndicadorInDB(**{"id_indicador": 9,
							"name":"Transferencias Electrónicas. Calidad lotes  aplicados",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Lotes aplicados / Lotes recibidos",
							"calculo":"Lotes aplicados: 27.969 Valor Total $394,793,643,710.10",
							"comentario":"Semana del 4 al 10 de junio",
							"ponderado":99.9,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador10": IndicadorInDB(**{"id_indicador": 10,
							"name":"Canje: Oportunidad compensación todas las Centrales.",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Servicios Operativos",
							"colorin":"3. Green",
							"formula":"Centrales de Canje con compensación canje / transmisión a Banco de la República oportunamente",
							"calculo":"Centrales de Canje: 38. 8 Cedec, 17 CUD o delegadas teercerizadas y 13 propias delegadas. Valor Canje Rec.: $97.539.323.795.91 Valor Canje Env.: $77.591.250.675.43",
							"comentario":"Semana del 03 al 09 junio",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
	"Indicador7": IndicadorInDB(**{"id_indicador": 7,
							"name":"Oportunidad en la atención de Embargos-Desembargos",
							"porcentaje":97.8,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Atención Requerimientos de Entes Extern",
							"colorin":"2. Yellow",
							"formula":"Embargos-Desembargos atendidos oportunamente / Total Embargos-Desembargos radicados *Fuente: Sistema de embargos",
							"calculo":"Identificaciones capturadas 7,771 Identificaciones oportunas(1-3 dias) 7,603 Identificaciones inoportunas(4 o mas dias) 150 Identificaciones pendientes  18",
							"comentario":"Identificaciones del 31 de Mayo al 6 de Junio de 2021",
							"ponderado":96.2,
							"lgreen":98,
							"lyellow":"92",
							"lred":92}),
	"Indicador5": IndicadorInDB(**{"id_indicador": 5,
							"name":"Atención casos escalados por OMAT por correo",
							"porcentaje":86.8,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte a Aplicaciones",
							"colorin":"2. Yellow",
							"formula":"# de casos atendidos / # casos escalados por OMAT por correo Fuente: Correos enviados por OMAT y registro de los casos atendidos en el grupo.",
							"calculo":"190 (# casos escalados por OMAT por correo)",
							"comentario":"Semana del 4 al 10 de junio",
							"ponderado":88.4,
							"lgreen":100,
							"lyellow":"76",
							"lred":76}),
	"Indicador6": IndicadorInDB(**{"id_indicador": 6,
							"name":"Cumplimiento de operaciones Clientes",
							"porcentaje":92.7,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Coordinación Moneda Extranjera",
							"colorin":"2. Yellow",
							"formula":"Operaciones para tramitar en el exterior/ Operaciones enviadas por oficinas.",
							"calculo":"Op. Recibidas de clientes 346 Op. Cumplidas 321 por valor de USD 4.023.406,69",
							"comentario":"Semana del 4 al 10 de junio",
							"ponderado":91.7,
							"lgreen":100,
							"lyellow":"90",
							"lred":90}),
	"Indicador11": IndicadorInDB(**{"id_indicador": 11,
							"name":"Oportunidad en conciliación",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Central de Cuadre",
							"colorin":"3. Green",
							"formula":"Canales  a conciliar (oficinas, centros de canje, cajeros corresponsales propios, Carvajal, Efectivo clientes,centros de efectivo,AFC,impuestos, ACH, transferencias ya, mi pago amigo ) / canales  conciliados",
							"calculo":"6,776 puntos conciliados 4,881 ajustes aplicados",
							"comentario":"Semana del 4 al 10 de junio",
							"ponderado":99.4,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
	"Indicador12": IndicadorInDB(**{"id_indicador": 12,
							"name":"Oportunidad en la inclusión de negociaciones vinculación Clientes Empresariales",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Supervisión Operativa Cash",
							"colorin":"3. Green",
							"formula":"Solicitudes atendidas oportunamente (Fuente Herramienta de negociación Star Cash (estado de la propuesta) / Total solicitudes recibidas (Fuente excel herremienta de gestión y Control Cash relación diaria)",
							"calculo":"142 Clientes",
							"comentario":"Semana del 4 al 10 de junio",
							"ponderado":99.8,
							"lgreen":100,
							"lyellow":"97.9",
							"lred":97.9}),
	"Indicador8": IndicadorInDB(**{"id_indicador": 8,
							"name":"Oportunidad transacciones atendidas en los tiempos definidos ANS",
							"porcentaje":98.0,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Centro Operación Empresarial  - Fiduciario",
							"colorin":"3. Green",
							"formula":"Transacciones cumplidas según ANS / solicitudes radicadas [Fuente: Excel - Inventario de solicitudes]",
							"calculo":"Acumulado :  Q  22,385   $ 8,2 Bll Semanal :  Q  1,153 $ 259 MMl",
							"comentario":"Semana 4 al 10 de junio",
							"ponderado":98.7,
							"lgreen":95,
							"lyellow":"90",
							"lred":90}),
	"Indicador13": IndicadorInDB(**{"id_indicador": 13,
							"name":"Oportunidad en el monitoreo de alertas operativas del canal",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "Soporte operativo Corresponsales Bancarios",
							"colorin":"3. Green",
							"formula":"Alertas gestionadas / Alertas generadas en el portal de monitoreo. Fuente porta monitoreo",
							"calculo":"Cantidad de alertas gestionadas 321",
							"comentario":"Semana del 4 al 10 de junio",
							"ponderado":109.8,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
	"Indicador14": IndicadorInDB(**{"id_indicador": 14,
							"name":"Oportunidad en el cumplimiento de operaciones del PF y otras Áreas adscritas al PF",
							"porcentaje":100,
							"gerencia":"Gerencia de Operación Bancaria",
							"central": "UAC Back Office",
							"colorin":"3. Green",
							"formula":"Número total operaciones cumplidas/ operaciones a cumplir.",
							"calculo":"631 Operaciones por un total de $7.251.122.034.180.73",
							"comentario":"Semana 4 al 10 de junio",
							"ponderado":100.0,
							"lgreen":100,
							"lyellow":"N/A",
							"lred":100}),
}

def get_indicador(indicador: str):
    if indicador in database_indicadores.keys():
        return database_indicadores[indicador]
    else:
        return None